name: 'Workflow Change Validation Checkout'
description: 'Checkout the wasmCloud repository, and add/replace GitHub pipeline assets, which require testing and validation'
inputs:
  fetch-depth:
    description: 'Number of commits to fetch. 0 fetches all history'
    required: false
    default: '1'
  fetch-tags:
    description: 'Whether to fetch all tags'
    required: false
    default: 'false'
  github_assets:
    description: 'List of .github assets to copy (path-qualified from .github/)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout wasmCloud repository
      uses: actions/checkout@v4
      with:
        repository: wasmCloud/wasmCloud
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: ${{ inputs.fetch-depth }}
        fetch-tags: ${{ inputs.fetch-tags }}

    - name: Checkout workflow validation repository
      uses: actions/checkout@v4
      with:
        path: doppleganger
        fetch-depth: ${{ inputs.fetch-depth }}
        fetch-tags: ${{ inputs.fetch-tags }}

    - name: Copy GitHub assets
      if: inputs.github_assets
      shell: bash
      run: |
        echo '${{ inputs.github_assets }}' | while read -r asset; do
          if [ ! -z "$asset" ]; then
            # Create directory if it doesn't exist
            mkdir -p "${{ github.workspace }}/.github/$(dirname $asset)"
            # Copy the file
            cp "${{ github.workspace }}/doppleganger/.github/$asset" "${{ github.workspace }}/.github/$asset"
          fi
        done
