name: 'Workflow Change Validation Checkout'
description: 'Checkout repository and validate workflow changes'

inputs:
  target-repo:
    description: 'Repository to test (e.g., https://github.com/user/repo)'
    required: true
    default: 'wasmCloud/wasmCloud'
  fetch-depth:
    description: 'Number of commits to fetch. 0 fetches all history'
    required: false
    default: '1'
  fetch-tags:
    description: 'Whether to fetch all tags'
    required: false
    default: 'false'
  github_assets:
    description: 'List of .github assets to copy (path-qualified from .github/)'
    required: false
  github-token:
    description: 'GitHub token for authentication'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.target-repo }}
        token: ${{ inputs.github-token }}
        fetch-depth: ${{ inputs.fetch-depth }}
        fetch-tags: ${{ inputs.fetch-tags }}

    - name: Checkout workflow validation repository
      uses: actions/checkout@v4
      with:
        path: dugout
        fetch-depth: ${{ inputs.fetch-depth }}
        fetch-tags: ${{ inputs.fetch-tags }}

    - name: Copy GitHub assets
      if: inputs.github_assets
      shell: bash
      run: |
        # Process JSON array of assets
        echo '${{ inputs.github_assets }}' | jq -r '.[]' | while read -r asset; do
          if [ ! -z "$asset" ]; then
            # Create directory if it doesn't exist
            mkdir -p "${{ github.workspace }}/.github/$(dirname $asset)"
            # Copy the file
            cp "${{ github.workspace }}/dugout/.github/$asset" "${{ github.workspace }}/.github/$asset"
          fi
        done
