name: 'SBOM Generation'
description: 'Generate SBOMs using cargo-sbom for Rust, k8s-sigs/bom for Go, and syft for other artifacts'
inputs:
  subject-name:
    description: 'Name of the artifact'
    required: true
  subject-path:
    description: 'Path to the built artifact (binary, image, etc.)'
    required: true
  package-name:
    description: 'For Rust: package name in Cargo.toml'
    required: false
  source-path:
    description: 'Path to source code or package manifest (e.g., directory containing Cargo.toml)'
    required: true
  package-version:
    description: 'Package version if not discoverable'
    required: false
  language:
    description: 'Language of the project (rust, go, other)'
    required: true

runs:
  using: "composite"
  steps:
    # Setup the directory all attestation and sbom artifacts are to be stored in,
    # if it doesn't exist. This will facilitate structured access across all workflows and actions.
    - name: Setup attestations-and-sboms directory
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/attestations-and-sboms
        echo "PROVENANCE_ARTIFACTS_DIR=${{ github.workspace }}/attestations-and-sboms" >> $GITHUB_ENV

    # Setup syft config from attest.yml
    - name: Setup Syft configuration
      if: inputs.language != 'rust' && inputs.language != 'go'
      shell: bash
      run: |
        cat > .syft.yaml << 'EOF'
        output:
          - spdx-json
        quiet: false
        scope: "squashed"
        format:
          spdx-json:
            pretty: true
        file:
          metadata:
            selection: "all"
            digests: ["sha256"]
            content:
              skip-files-above-size: 10485760
        source:
          name: ${{ inputs.subject-name }}
          version: ${{ inputs.package-version }}
          base-path: ${{ inputs.source-path }}
        log:
          structured: true
          level: "error"
          file: ""
        EOF

    # For Rust projects
    - name: Install cargo-sbom
      if: inputs.language == 'rust'
      shell: bash
      run: cargo install --version 0.9.1 cargo-sbom

    - name: Generate ${{ inputs.package-name }} Rust SBOM
      if: inputs.language == 'rust'
      shell: bash
      run: |
        if [ -n "${{ inputs.package-name }}" ]; then
          cargo sbom \
            --cargo-package ${{ inputs.package-name }} \
            --output-format spdx_json_2_3 \
            --project-directory ${{ github.workspace }}/${{ inputs.source-path }} \
            > "${{ env.PROVENANCE_ARTIFACTS_DIR }}/${{ inputs.subject-name }}.spdx.json"
        else
          cargo sbom \
            --output-format spdx_json_2_3 \
            --project-directory ${{ github.workspace }}/${{ inputs.source-path }} \
            > "${{ env.PROVENANCE_ARTIFACTS_DIR }}/${{ inputs.subject-name }}.spdx.json"
        fi

    # For Go projects
    - name: Install k8s-sigs/bom
      if: inputs.language == 'go'
      shell: bash
      run: go install sigs.k8s.io/bom/cmd/bom@latest

    - name: Generate ${{ inputs.subject-name }} Go SBOM
      if: inputs.language == 'go'
      shell: bash
      run: |
        bom generate \
          --namespace "https://wasmcloud.com" \
          --name "${{ inputs.subject-name }}" \
          --dirs "${{ github.workspace }}/${{ inputs.source-path }}" \
          --format json
          --output "${{ env.PROVENANCE_ARTIFACTS_DIR }}/${{ inputs.subject-name }}.spdx.json"

    # For other artifacts using Anchore's action
    - name: Generate ${{ inputs.subject-name }} SBOM using Syft
      if: inputs.language != 'rust' && inputs.language != 'go'
      uses: anchore/sbom-action@v0
      with:
        path: ${{ github.workspace }}/${{ inputs.source-path }}
        artifact-name: ${{ inputs.subject-name }}.sbom
        format: spdx-json
        config: .syft.yaml
        output-file: ${{ env.PROVENANCE_ARTIFACTS_DIR }}/${{ inputs.subject-name }}.spdx.json

    # Upload the SBOM to common artifact storage
    - name: Upload ${{ inputs.subject-name }} SBOM
      if: hashFiles(format('{0}.spdx.json', inputs.subject-name)) != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.subject-name }}.spdx.json
        path: ${{ env.PROVENANCE_ARTIFACTS_DIR }}/${{ inputs.subject-name }}.spdx.json
        if-no-files-found: warn
        overwrite: true