name: 'Generate SBOM and Attestations'
description: 'Creates SBOMs and attestations for wasmCloud artifacts'

inputs:
  artifact-path:
    required: true
    description: "Path to the artifact (binary or OCI image) to attest"
  artifact-name:
    required: true
    description: "Name of the artifact"
  artifact-type:
    required: true
    description: "Type of artifact: 'binary', 'oci', or 'source'"
  subject-digest:
    required: false
    description: "Required for OCI: SHA256 digest of the image"
  generate-sbom:
    required: false
    default: 'false'
    description: "Whether to generate SBOM for this artifact"
  is-rust:
    required: false
    default: 'true'
    description: "Whether this is a Rust package"
  package-name:
    required: false
    description: "For Rust packages: name in Cargo.toml"
  package-version:
    required: false
    description: "The package version"
  package-path:
    required: false
    description: "For non-Rust packages: path to package source"
  sbom-output-path:
    required: false
    default: 'sbom'
    description: "Directory to store generated SBOM"

runs:
  using: "composite"
  steps:
    # Copy the steps from the workflow here, but remove the job/workflow level configuration
    - name: Install cargo-sbom
      if: inputs.generate-sbom == 'true' && inputs.is-rust == 'true'
      shell: bash
      run: cargo install --version 0.9.1 cargo-sbom

    # ... rest of the steps ... 