name: "Publish SBOMs and Attestations"
description: "Create OCI artifact containing SBOMs and attestations with proper annotations"
inputs:
  subject-name:
    description: "Name of the subject for the artifact"
    required: true
  release-version:
    description: "Version tag for the artifact"
    required: true
  registry:
    description: "Target registry for the artifact"
    required: true
    default: "ghcr.io"
  registry-credentials:
    description: "JSON array of registry credentials [{url, username, password}]"
    required: false
  show-metadata:
    description: "Whether to print artifacts metadata after creation"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    # Setup the directory all attestation and sbom artifacts are to be stored in,
    # if it doesn't exist. This will facilitate structured access across all workflows and actions.
    - name: Setup attestations-and-sboms directory
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/attestations-and-sboms
        echo "PROVENANCE_ARTIFACTS_DIR=${{ github.workspace }}/attestations-and-sboms" >> $GITHUB_ENV

    - name: Install regctl
      shell: bash
      run: |
        curl -s -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 -o /usr/local/bin/regctl
        chmod +x /usr/local/bin/regctl

    - name: Download Attestation artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: "*-attestation.json"
        path: ${{ env.PROVENANCE_ARTIFACTS_DIR }}
        merge-multiple: true

    - name: Download SBOM artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: "*.spdx.json"
        path: ${{ env.PROVENANCE_ARTIFACTS_DIR }}
        merge-multiple: true

    - name: Download attestation metadata artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: "*-attestation-metadata.yaml"
        path: ${{ env.PROVENANCE_ARTIFACTS_DIR }}
        merge-multiple: true

    - name: Cleanup artifacts
      shell: bash
      run: |
        echo "Separating SBOM and attestation artifacts for wasmcloud and wash-cli"
        if [[ "${{ inputs.subject-name }}" == "wash-cli" ]]; then
          # delete any files that its name does not start with `wash`
          find ${{ env.PROVENANCE_ARTIFACTS_DIR }} -type f ! -name 'wash-*' -delete
        else
          # delete any files that its name does start with `wash` (i.e. keep wasmcloud and providers)
          find ${{ env.PROVENANCE_ARTIFACTS_DIR }} -type f -name 'wash-*' -delete
        fi

    - name: Create provenance:${{ inputs.release-version }} OCI artifact image
      shell: bash
      run: |
        echo "Creating provenance:${{ inputs.release-version }} OCI artifact image"
        # Create empty OCI directory
        regctl image create ocidir://${{ inputs.subject-name }}-provenance:${{ inputs.release-version }}

        # Process each SBOM
        find ${{ env.PROVENANCE_ARTIFACTS_DIR }} -name "*.spdx.json" -type f | while read sbom_file; do
          base_name=$(basename "$sbom_file" .spdx.json)
          metadata_file="${{ env.PROVENANCE_ARTIFACTS_DIR }}/${base_name}-attestation-metadata.yaml"

          # Extract metadata if available
          if [ -f "$metadata_file" ]; then
            subject_name=$(yq -r '.subject_name' "$metadata_file")
            subject_digest=$(yq -r '.subject_digest' "$metadata_file")
          else
            subject_name="${base_name}"
            subject_digest=""
          fi

          # Add SBOM as artifact with annotations
          regctl artifact put \
            --strip-dirs \
            --index \
            --artifact-type="application/spdx+json" \
            --config-type="application/vnd.oci.empty.v1+json" \
            --file-title \
            --file-media-type="application/spdx+json" \
            --file "$sbom_file" \
            --subject ocidir://${{ inputs.subject-name }}-provenance:${{ inputs.release-version }} \
            --annotation "org.opencontainers.artifact.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            --annotation "org.opencontainers.artifact.description=SPDX SBOM for ${subject_name}" \
            --annotation "org.opencontainers.artifact.type=spdx.sbom" \
            ${subject_digest:+"--annotation"} ${subject_digest:+"org.opencontainers.artifact.ref=${subject_digest}"}
        done

        # Process each attestation
        find ${{ env.PROVENANCE_ARTIFACTS_DIR }} -name "*-attestation.json" -type f | while read attestation_file; do
          base_name=$(basename "$attestation_file" -attestation.json)
          metadata_file="${{ env.PROVENANCE_ARTIFACTS_DIR }}/${base_name}-attestation-metadata.yaml"

          # Extract metadata
          if [ -f "$metadata_file" ]; then
            artifact_type=$(yq -r '.artifact_type' "$metadata_file")
            subject_name=$(yq -r '.subject_name' "$metadata_file")
            subject_digest=$(yq -r '.subject_digest' "$metadata_file")
            attestation_id=$(yq -r '.attestation_id' "$metadata_file")
          else
            artifact_type="unknown"
            subject_name="${base_name}"
            subject_digest=""
            attestation_id="unknown"
          fi

          # Add attestation as artifact with annotations
          regctl artifact put \
            --strip-dirs \
            --index \
            --artifact-type="application/json" \
            --config-type="application/vnd.oci.empty.v1+json" \
            --file-title \
            --file-media-type="application/json" \
            --file "$attestation_file" \
            --subject ocidir://${{ inputs.subject-name }}-provenance:${{ inputs.release-version }} \
            --annotation "org.opencontainers.artifact.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            --annotation "org.opencontainers.artifact.description=Attestation for ${subject_name} ${artifact_type^^}" \
            --annotation "org.opencontainers.artifact.type=in-toto.attestation" \
            --annotation "github.attestation.id=${attestation_id}" \
            ${subject_digest:+"--annotation"} ${subject_digest:+"org.opencontainers.artifact.ref=${subject_digest}"}
        done

    # Show metadata if requested
    - name: Show image metadata
      if: inputs.show-metadata == 'true'
      shell: bash
      run: |
        echo "Showing image metadata"
        IMAGE_PATH="ocidir://${{ inputs.subject-name }}-provenance:${{ inputs.release-version }}"

        echo "=== OCI Artifact Index ==="
        regctl artifact list ${IMAGE_PATH} -v error | yq -P
        echo

        # echo "=== Processing Individual Artifacts ==="
        # for digest in $(regctl artifact list ${IMAGE_PATH} -v error | yq -r '.Referrers | with_entries(select(.key | test("Digest"))) | to_entries | .[].value'); do
        #   echo "=== Artifact for $digest ==="
        #   regctl blob get ${IMAGE_PATH} ${digest} -v error | yq -P
        #   echo
        # done

    - name: Push artifact to registry
      if: inputs.registry-credentials
      shell: bash
      run: |
        echo "Pushing artifact to registry"
        # Login to registry
        echo "${{ inputs.registry-credentials }}" | jq -r '.[] | "\(.url) \(.username) \(.password)"' | while read url username password; do
          echo "Logging in to $url"
          echo "$password" | regctl registry login -u "$username" --pass-stdin "$url"
        done

        yq --version
        jq --version
        regctl image manifest ocidir://${{ inputs.subject-name }}-provenance:${{ inputs.release-version }} -v error | yq -P

        # Push the artifact
        regctl image copy \
          ocidir://${{ inputs.subject-name }}-provenance:${{ inputs.release-version }} \
          ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.subject-name }}-provenance:${{ inputs.release-version }} \
          --digest-tags \
          --referrers
